[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 150
solc = "0.8.23"
evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
mumbai = { key = "${POLYGONSCAN_API_URL}" }

[profile.optimized]
via_ir = true