[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 150
solc = "0.8.23"
evm_version = "shanghai"
fs_permissions = [{ access = "read-write", path = "./deployments/"}]

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"

[profile.optimized]
via_ir = true