[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 100
solc = "0.8.23"
evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@tangible/=lib/tnftv2-audit/contracts/",
    "@chainlink/=lib/chainlink/",
    "@tangible-foundation-contracts/=lib/tangible-foundation-contracts/src/",
    "@vrf/=lib/vrf-contracts"
]

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
mumbai = { key = "${POLYGONSCAN_API_URL}" }

[profile.optimized]
via_ir = true