name: test

on:
  push:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Baskets Foundry Projects
    runs-on: ubuntu-latest
    env:
      POLYGONSCAN_API_URL: ${{ vars.POLYGONSCAN_API_URL }}
      MUMBAI_RPC_URL: ${{ vars.MUMBAI_RPC_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          echo "MUMBAI_RPC_URL: $MUMBAI_RPC_URL"
          echo "POLYGONSCAN_API_URL: $POLYGONSCAN_API_URL"
          forge test
        id: test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
